### ISSUE TITLE
Uncaught Error: [$injector:nomod] Module 'app.layout' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

### ISSUE THREAD

**Issue by arnorhaux** [johnpapa/ng-demos#28]
Hi John

I noticed that you blogged about this error when injecting angular modules in your project:

http://www.johnpapa.net/easy-fix-to-a-common-angular-module-error/

Uncaught Error: [$injector:nomod] Module 'app.layout' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

What I did was adding '[]' to every line where angular module would be declared for example:

```
angular
    .module('app.layout',[])
    .controller('Shell', Shell);
```

And the error would disappear.

Do you think this is related to mixing versions of js files if I add them with nuget?

**Comment by DonnieLai** [comment]
I have a similar problem.
And I did as you told. But under Firefox is feasible, IE8 is still reported wrong
