### ISSUE TITLE
Using Jade templates

### ISSUE THREAD

**Issue by vcardins** [johnpapa/ng-demos#48]
Could you give a clue on how to use Jade templates instead?

**Comment by wardbell** [comment]
Why does this interest you? Almost nothing happens in the single web page that "hosts" the SPA. Are you thinking about coding templates in jade? What are the benefits?

**Comment by vcardins** [comment]
It is just a matter of preference, the code looks cleaner to me. I'm not really requesting to use Jade in the demos instead, but actually a help on how I could change the gulpfile to make it work.
Thanks

**Comment by biswajitpanday** [comment]
You can go through this link. I hope this would help you a lot.
http://www.clock.co.uk/blog/a-simple-website-in-nodejs-with-express-jade-and-stylus
