### ISSUE TITLE
common vs blocks

### ISSUE THREAD

**Issue by chavz** [johnpapa/ng-demos#53]
Just like #45 , this is just a general question regarding the app architecture, i'm confused on what is the difference between `common` and `blocks` as they seem similar in being reusable.

I'm actually struggling on where to put helper functions (filters, value services, etc) I created for 3rd-party libraries I'm using, and I'm thinking of putting it in `common`, would that be a correct approach ? and if so, should I probably have create them under separate modules just like how `blocks` are ?

**Comment by johnpapa** [comment]
I dont use common .... in fact I should chuck it from this repo and its projects. So where do they go?

- filters ... if needed by a specific module, put it in there. If more generic, put it in the core module. If there are many filters that are generic, put it in a module of shared filters.
- directives ... see above
- values/constants ... see above, but I usually stop at core

blocks are just a naming convention for code that can be used across many projects.

**Comment by chavz** [comment]
I see, thanks for the explanation!
